# Generated by Django 6.0.4 on 2026-04-20 11:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField(default=django.utils.timezone.now)),
                ('quantity_g', models.PositiveIntegerField(help_text='Quantity of the harvest in grams')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MushroomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=100)),
                ('growing_days', models.IntegerField(help_text='Days from spawning to harvest')),
                ('selling_price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product/Item name', max_length=200)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('reorder_level', models.PositiveIntegerField(default=5, help_text='Alert when stock falls below this level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_quantity_g', models.PositiveIntegerField(default=0)),
                ('last_purchase_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-total_purchases'],
                'indexes': [models.Index(fields=['mobile'], name='farm_manage_mobile_e8d108_idx'), models.Index(fields=['name'], name='farm_manage_name_4d056d_idx')],
            },
        ),
        migrations.CreateModel(
            name='MushroomInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField()),
                ('quantity_g', models.PositiveIntegerField(help_text='Quantity in grams')),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_harvest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_records', to='farm_management.harvest')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_mobile', models.CharField(max_length=20)),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('sale_quantity_g', models.PositiveIntegerField(help_text='Quantity in grams')),
                ('sale_amount', models.DecimalField(decimal_places=2, help_text='Total sale amount in ₹', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='farm_management.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('upi', 'UPI')], max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='farm_management.sale')),
            ],
        ),
        migrations.CreateModel(
            name='SpawnBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.PositiveIntegerField(unique=True)),
                ('batch_date', models.DateField()),
                ('substrate_type', models.CharField(choices=[('straw', 'Straw'), ('pellet', 'Pellet'), ('sawdust', 'Sawdust')], default='straw', max_length=20)),
                ('number_of_bags', models.PositiveIntegerField(default=0)),
                ('no_spawns_used', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('harvested', 'Harvested'), ('completed', 'Completed')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mushroom_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_management.mushroomtype')),
            ],
        ),
        migrations.AddField(
            model_name='harvest',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='farm_management.spawnbatch'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('substrate', 'Substrate Materials'), ('spawn', 'Spawn Purchase'), ('labor', 'Labor Cost'), ('equipment', 'Equipment'), ('utilities', 'Utilities'), ('packaging', 'Packaging'), ('transport', 'Transportation'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('receipt', models.FileField(blank=True, upload_to='receipts/')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm_management.stock')),
            ],
        ),
    ]
