# Generated by Django 6.0.4 on 2026-04-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spawnbatch',
            name='mushroom_type',
            field=models.CharField(choices=[('oyster', 'oyster'), ('pellet', 'Pellet'), ('sawdust', 'Sawdust')], default='oyster', max_length=20),
        ),
    ]
