# Generated by Django 6.0.4 on 2026-04-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0002_alter_spawnbatch_mushroom_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spawnbatch',
            name='mushroom_type',
            field=models.CharField(choices=[('oyster', 'Oyster Mushroom')], default='oyster', max_length=20),
        ),
    ]
