# Generated by Django 6.0.4 on 2026-04-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0003_alter_spawnbatch_mushroom_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='spawnbatch',
            name='number_of_bags_contaminated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spawnbatch',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('incubation', 'Incubation'), ('fruiting', 'Fruiting'), ('harvesting', 'Harvesting'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
