# Generated by Django 6.0.4 on 2026-04-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0004_spawnbatch_number_of_bags_contaminated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='created_by',
            new_name='sold_by',
        ),
        migrations.AddField(
            model_name='sale',
            name='partially_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Partial payment amount in ₹', max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('notpaid', 'Not Paid'), ('partiallypaid', 'Partially Paid')], default='paid', max_length=20),
        ),
    ]
