# Generated by Django 6.0.4 on 2026-04-27 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0005_rename_created_by_sale_sold_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sold_by',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='partially_paid_amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='payment_status',
        ),
    ]
