# Generated by Django 6.0.4 on 2026-04-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0007_sale_sold_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='partial_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='amount in ₹', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid')], default='paid', max_length=20),
        ),
    ]
