# Generated by Django 6.0.4 on 2026-04-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0008_sale_partial_payment_amount_sale_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='partial_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='amount in ₹', max_digits=12, null=True),
        ),
    ]
