# Generated by Django 6.0.4 on 2026-05-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0009_alter_sale_partial_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='spawnbatch',
            name='number_of_bags_completed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
